- libmate-desktop/mate-colorseldialog.c
- libmate-desktop/mate-colorseldialog.h
- tools/mate-color-select.c
maybe it was relevant with GTK+ 3.12 where the developers forced
CSD on all dialogs, but now it isn't. in GTK+ 3.14 they apparently
realized they were wrong and stopped forcing CSD on dialogs:
http://blogs.gnome.org/mclasen/2014/07/28/a-talk-in-9-images/
> color select dialog: drop CSD/headerbar usage

- libmate-desktop/mate-aboutdialog.c
- libmate-desktop/mate-colorsel.c
Such typedefs are in corresponding header files.
> Remove duplicated typedef

- libmate-desktop/mate-bg.c
This reverts commit 48df7a0c71a2df4050abae40ec9ca2b35dee7988.
The commit causes a regression with timing xml backgrounds.
see https://github.com/mate-desktop/mate-control-center/issues/159
> Revert "changed checking for NULL a bit"

- libmate-desktop/mate-aboutdialog.c
- libmate-desktop/mate-colorsel.c
- libmate-desktop/mate-colorsel.h
and fix deprecated usage of GtkHBox and GtkVBox in GTK+3 build
NOTE: this commit changes the public interface of the library
@raveit65 @lukefromdc please test for any possible issues... what might be affected are color selection dialogs in eom, mate-panel and netspeed applet. All seem to work fine here though.
> use GtkBox instead of GtkVBox in both GTK+ builds

- libmate-desktop/mate-bg-crossfade.c
- libmate-desktop/mate-bg.c
- libmate-desktop/mate-bg.h
For this change there is some more work in other packages needed.
```
[rave@mother github-matedesktop]$ grep -nr libmate-desktop/mate-bg *
caja/libcaja-private/caja-directory-background.c:42:#include <libmate-desktop/mate-bg.h>
caja/src/caja-application.c:78:#include <libmate-desktop/mate-bg.h>
caja/eel/eel-background.c:43:#include <libmate-desktop/mate-bg.h>
caja/eel/eel-background.h:51:#include <libmate-desktop/mate-bg.h>
mate-control-center/capplets/appearance/mate-wp-item.h:26:#include <libmate-desktop/mate-bg.h>
mate-control-center/capplets/appearance/appearance-desktop.c:31:#include <libmate-desktop/mate-bg.h>
mate-panel/mate-panel/panel-background-monitor.c:36:#include <libmate-desktop/mate-bg.h>
mate-screensaver/src/gs-manager.c:32:#include <libmate-desktop/mate-bg.h> …
```
> port GdkColors to GdkRGBA

- libmate-desktop/mate-bg.c
Fixes https://github.com/mate-desktop/mate-desktop/issues/237
Another gtk2 regression with caja.
This fixes the issue for me with using a dark gtk theme and setting a dark bg via 'Emplems and Backgrounds'.
Tested on top of 1.16, hope we don't get any fallout in other places.
@monsta 
Please test
> GTK+-2: fix fontcolor for dark bg in caja

- libmate-desktop/mate-bg-crossfade.c
- libmate-desktop/mate-bg-crossfade.h
- libmate-desktop/mate-bg.c
This fixes directory background drawing in #506, fixes compiz-reloaded/compiz#40 (desktop background issues with Compiz 0.8.x) and fixes background fading.
Caja now draws the desktop background again and the gap in code between GTK+ 3.22 and previous versions is removed.
Other parts of the change: mate-desktop/caja#731, mate-desktop/mate-settings-daemon#169.
> Fixes for background drawing

- libmate-desktop/mate-aboutdialog.c
> mate-aboutdialog: Fix url is not centered

- man/mate-about.1
The command mate-about doesn't recognize the option --mate-version, it works with --version
> Correct little imprecision in man mate-about

- libmate-desktop/mate-aboutdialog.c
- libmate-desktop/mate-desktop-item.c
Please test.
The change in mate-aboutdialog.c can't be tested any more as all MATE applications use gtk_about now.
We need to remove that lib, before someone other starts to fix more deprecations here ;)
@monsta thoughts ?
Honestly, i have no idea where/for what mate-desktop-item.c is used and how we can test this uri change. Any ways, using *NULL* here should be save.
> gtk show uri deprecations

- libmate-desktop/mate-bg.c
- libmate-desktop/mate-rr-labeler.c
avoid deprecated:
gdk_screen_get_monitor_geometry
gdk_screen_get_monitor_at_point
> gtk 3.22: avoid deprecated gdk_screen_get_monitor... functions:

- libmate-desktop/mate-bg.c
- libmate-desktop/mate-colorsel.c
- libmate-desktop/mate-rr-labeler.c
This commit reverts:
https://github.com/mate-desktop/mate-desktop/commit/6137212bce120c9eb5555ae777fc7fea2f71e43e
And it applies an alternative to fix the deprecated functions:
gdk_screen_get_width
gdk_screen_get_height
> WidthOfScreen and HeightOfScreen implementation

- NEWS
- configure.ac
- schemas/org.mate.interface.gschema.xml.in
it doesn't work with GTK+3, see https://github.com/mate-desktop/atril/issues/247, https://github.com/mate-desktop/mate-calc/issues/30, https://github.com/mate-desktop/mate-desktop/issues/296
this PR bumps version so that m-s-d can rely on it
> drop non-working can-change-accels option from GSettings

- libmate-desktop/mate-rr-labeler.c
Fixes https://github.com/ubuntu-mate/ubuntu-mate-artwork/issues/29
This fixes wrong font-color for monitor info popup for all dark themes.
Issue was caused by a last missing port to GdkRGBA color.
Note:
....i know that gtk_widget_override_color {} is deprecated too, but i don't know how to replace it.
> mate-rr-labeler: fix font-color for dark themes

- schemas/org.mate.peripherals-mouse.gschema.xml.in
The MATE cursor theme does not have an 18px cursor size, so having
a 18px as the default setting does not make sense. Using 24px looks
better in modern displays and allows for proper HiDPI scaling.
Relevant: mate-desktop/mate-control-center/pull/342
> Change default cursor-size to 24px

- schemas/org.mate.interface.gschema.xml.in
When enabled (default), m-s-d will attempt to set QT_SCALE_FACTOR during the init phase.
When disabled, the user can then choose to control this env var elsewhere.
* Requires mate-desktop/mate-settings-daemon/pull/225
* Fixes mate-desktop/mate-session-manager/issues/158
> Add toggle for synchronizing QT_SCALE_FACTOR to GDK_SCALE_FACTOR

- schemas/org.mate.interface.gschema.xml.in
Needed for https://github.com/mate-desktop/mate-settings-daemon/pull/234   Default is "enabled" to avoid any change in expected behavior with a default install.
> interface: add key to enable/disable primary paste from middlemouse

- schemas/org.mate.accessibility-keyboard.gschema.xml.in
Add new setting *org.mate.accessibility-keyboard.stickykeys-latch-to-lock* to control whether latching is enabled together with sticky keys.
Default value is for compatibility with current behavior, although I'd rather see that disabled by default as it is fairly confusing for the newcomer.
See https://github.com/mate-desktop/mate-settings-daemon/pull/237 and https://github.com/mate-desktop/mate-control-center/pull/374.
> Add new setting to control XKB modifier latching

- schemas/Makefile.am
- schemas/org.mate.applications-calculator.gschema.xml.in
• Defines a schema that allows users to specify a default calculator application.
• Default initialized to 'galculator'.
• By itself, this PR does not change much. However, it allows for other relevant PRs to act on the existence of this schema.
• Will open PR at https://github.com/mate-desktop/mate-control-center to open a PR to control the schema
• Will open PR at https://github.com/mate-desktop/mate-settings-daemon to update https://github.com/mate-desktop/mate-settings-daemon/blob/master/plugins/media-keys/msd-media-keys-manager.c to honor the schema as opposed to the following behavior:
1. Execute 'galculator', if available.
2. If 'galculator' is not available, execute 'mate-calc', if available.
3. If 'mate-calc' is not available, execute 'gnome-calculator', if available.
4. If …
> schemas: Define schema for a default calculator

- libmate-desktop/mate-bg.c
There are some incorrect comments in mate_bg_create_surface_scale. Fix them.
> mate-bg: Corrected some comments

- libmate-desktop/mate-colorsel.c
The expected: the same colors here:
> mate-colorsel: avoid deprecated 'gtk_widget_modify_bg'

- libmate-desktop/mate-hsv.c
```
mate-hsv.c:913:19: warning: Value stored to 'priv' during its initialization is never read
MateHSVPrivate *priv = hsv->priv;
^~~~   ~~~~~~~~~
```
> mate-hsv: avoid duplicate initialization in variable

- libmate-desktop/test-ditem.c
Fixes Clang static analyzer warning:
```
test-ditem.c:94:2: warning: Call to function 'strcat' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcat'. CWE-119
strcat (path, "/foo.desktop");
^~~~~~
```
> [Security] test-ditem: Use 'g_strlcat' instead of 'strcat'

- libmate-desktop/mate-desktop-item.c
- libmate-desktop/mate-rr-config.c
Fixes Clang static analyzer warnings:
```
mate-rr-config.c:549:3: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
strcpy (output->priv->vendor, "???");
^~~~~~
mate-desktop-item.c:2118:2: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
strcpy (the_exec, exec);
^~~~~~
```
> [Security] Use 'g_strlcpy' instead of 'strcpy'

- libmate-desktop/mate-bg.c
Fixes Clang static analyzer warning:
```
mate-bg.c:2764:2: warning: Potential leak of memory pointed to by 'size'
g_queue_push_tail (parser->stack, g_strdup (name));
^~~~~~~~~~~~~~~~~
```
> mate-bg: Fix memory leak

- libmate-desktop/mate-thumbnail-pixbuf-utils.c
Fixes Clang static analyzer warning:
```
mate-thumbnail-pixbuf-utils.c:160:17: warning: Division by zero
*dest++ = r / n_pixels;
~~^~~~~~~~~~
```
> mate-thumbnail-pixbuf-utils: Fix division by zero

- libmate-desktop/mate-desktop-thumbnail.c
Fixes Clang static analyzer warning:
```
mate-desktop-thumbnail.c:933:54: warning: Null pointer passed as an argument to a 'nonnull' parameter
g_checksum_update (checksum, (const guchar *) uri, strlen (uri));
^~~~~~~~~~~~
```
This function is used in `caja` and `eom`:
> mate-desktop-thumbnail: avoid 'NULL' parameter

- libmate-desktop/Makefile.am
Fixes https://github.com/zhuyaliang/user-admin/issues/21
Signed-off-by: Marty E. Plummer <hanetzer@startmail.com>
> build: use localedir instead of DATADIRNAME

- .travis.yml
the icon name was changed since the commit:
https://github.com/mate-desktop/mate-desktop/commit/d83bccb64d612034be471c0724edd129519c3584
and it was moved with the commit:
https://github.com/mate-desktop/mate-desktop/commit/6109546780fde4bc8e9986c3f258960a5fdd76bf
https://mate-desktop.mate-desktop.dev
before:
later:
> Travis CI: Fix icon name

- configure.ac
I think this can be dropped because help is in mate-user-guide.
This was added and already mentioned here.
https://github.com/mate-desktop/mate-desktop/pull/376#pullrequestreview-242001373
Please review.
> configure: drop check for itstool

- mate-about/mate-about.h
Now the official web site is https://mate-desktop.org/.
> Change url project's website

- po/POTFILES.in
- schemas/Makefile.am
- schemas/meson.build
- schemas/org.mate.applications-messenger.gschema.xml
Defines a schema that allows users to specify a default instant messaging application.
Default initialized to 'pidgin'.
> schemas: Define schema for a default messenger

- .travis.yml
This is better because `ninja -C _build dist` do not create auto-generated files
> using autotools to generate tarballs

- .travis.yml
- configure.ac
- icons/Makefile.am
EDIT: in https://github.com/mate-desktop/mate-desktop/pull/369 the PNG icons are created if they are not present in icon folder, so, we don't need it in normal build: https://github.com/mate-desktop/mate-desktop/pull/369#issuecomment-475062827
> make 'rsvg-convert' optional

- meson.build
Bump the version in meson.build to 1.23.2 (same as in configure.ac).
Otherwise meson builds break building anything that depends on mate-desktop 1.23.2 , and mate-about displays version 1.23.1 instead of 1.23.2 in meson builds
> meson: fix build version

- configure.ac
- mate-about/Makefile.am
- mate-about/mate-about.h.in
- mate-about/meson.build
Test 1:
```
./autogen.sh --prefix=/usr
cat mate-about/mate-about.h
make && sudo make install
```
Test 2:
```
mkdir builddir
meson setup builddir --prefix=/usr
cat builddir/mate-about/mate-about.h
sudo ninja -C builddir install
```
> build: introduce RELEASE_YEAR variable for mate-about dialog

- libmate-desktop/mate-colorsel.c
- libmate-desktop/mate-desktop-thumbnail.c
Fixes the warnings:
```
mate-desktop-thumbnail.c:71:29: warning: redundant redeclaration of 'mate_desktop_thumbnail_factory_init' [-Wredundant-decls]
mate-desktop-thumbnail.c:71:29: warning: redundant redeclaration of 'mate_desktop_thumbnail_factory_class_init' [-Wredundant-decls]
mate-colorsel.c:198:14: warning: redundant redeclaration of 'set_focus_line_attributes' [-Wredundant-decls]
```
> avoid redundant redeclarations

- configure.ac
- mate-about/Makefile.am
- tools/Makefile.am
```shell
$ ./autogen.sh --enable-compile-warnings=maximum --enable-debug
<cut>
mate-desktop 1.23.3
===================
prefix:                       /usr/local
exec_prefix:                  ${prefix}
libdir:                       ${exec_prefix}/lib
bindir:                       ${exec_prefix}/bin
sbindir:                      ${exec_prefix}/sbin
sysconfdir:                   ${prefix}/etc
localstatedir:                ${prefix}/var
datadir:                      ${datarootdir}
source code location:         .
compiler:                     gcc
cflags:                        -g -O0
warning flags:                -Wall -Wmissing-prototypes -Wbad-function-cast -Wcast-align -Wextra -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wpointer-arith …
```
> Compiler flags

- configure.ac
- mate-about/meson.build
Whilst working on the [Reproducible Builds](https://reproducible-builds.org/) effort I noticed that mate-desktop could not be built reproducibly.
This is is because it generated a "release year" based on the current build date which was embedded in the binary and possibly other files. A patch attached that uses [SOURCE_DATE_EPOCH](https://reproducible-builds.org/specs/source-date-epoch/) instead.
As a side-effect, this fixes the (accidental) reset of `MATE_DATE` in the Autotools build system in inherited from `mate-desktop-environment.git`.
This was originally filed in Debian as [#951357](https://bugs.debian.org/951357).
> Make the build reproducible

- Makefile.am
- docs/reference/mate-desktop/Makefile.am
- icons/Makefile.am
- libmate-desktop/Makefile.am
- man/Makefile.am
- mate-about/Makefile.am
- schemas/Makefile.am
- tools/Makefile.am
fixes https://github.com/mate-desktop/mate-desktop/issues/431
I am not sure if adding the meson files for `po` and `utils` dir were correct.
```
EXTRA_DIST = \
abi-check \
autogen.sh \
config.meson.h\
COPYING-DOCS \
meson.build \
meson_options.txt \
po/meson.build \
utils/post_install.py
```
> build: add meson config files to EXTRA_DIST

- mate-about/mate-about.c
```
mate-about.c:35:16: warning: unused variable ‘window’ [-Wunused-variable]
35 |     GtkWidget* window;
|                ^~~~~~
```
> mate-about: remove unused variable ‘window’

- libmate-desktop/mate-bg.c
- libmate-desktop/mate-desktop-item.c
```
mate-bg.c:2976:37: warning: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(void *, void *)’ [-Wcast-function-type]
2976 |  g_list_foreach (show->stack->head, (GFunc) g_free, NULL);
|                                     ^
--
mate-desktop-item.c:876:33: warning: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(void *, void *)’ [-Wcast-function-type]
876 |  g_list_foreach (section->keys, (GFunc)g_free, NULL);
|                                 ^
--
mate-desktop-item.c:900:35: warning: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(void *, void *)’ [-Wcast-function-type]
900 |  g_list_foreach (item->languages, (GFunc)g_free, NULL);
|                                   ^
mate-desktop-item.c:904:30: …
```
> Remove warnings: cast between incompatible function types

- libmate-desktop/mate-bg.c
```
mate-bg.c:618:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
618 | get_wallpaper_cache_dir ()
| ^~~~~~~~~~~~~~~~~~~~~~~
```
> mate-bg: remove warning function declaration isn’t a prototype

- libmate-desktop/mate-desktop-thumbnail.c
```
find . \( -name '*.h' -o -name '*.c' \) -exec sed -i 's/[[:space:]]*$//' {} \;
find . \( -name '*.h' -o -name '*.c' \) -exec sed -i 's/\t*$//' {} \;
```
> mate-desktop-thumbnail: Remove trailing spaces/tabs

- NEWS
- configure.ac
- meson.build
- schemas/org.mate.accessibility-keyboard.gschema.xml
Add *capslock-beep-enable* gsetting, and bump the version to allow other component to require it.
Required by https://github.com/mate-desktop/mate-settings-daemon/pull/330 and https://github.com/mate-desktop/mate-control-center/pull/583.
> a11y-keyboard: Add capslock-beep-enable gsetting

- libmate-desktop/mate-bg.c
- libmate-desktop/mate-colorsel.c
- libmate-desktop/mate-hsv.c
- libmate-desktop/mate-languages.c
```
mate-bg.c: In function ‘get_pixbuf_for_size’:
mate-bg.c:2383:30: warning: cast from function call of type ‘double’ to non-matching type ‘unsigned int’ [-Wbad-function-cast]
2383 |     time_until_next_change = (guint)get_slide_timeout (slide);
|                              ^
mate-languages.c: In function ‘count_languages_and_territories’:
/usr/lib64/glib-2.0/include/glibconfig.h:98:37: warning: cast from function call of type ‘gpointer’ {aka ‘void *’} to non-matching type ‘long int’ [-Wbad-function-cast]
98 | #define GPOINTER_TO_INT(p) ((gint)  (glong) (p))
|                                     ^
mate-languages.c:576:12: note: in expansion of macro ‘GPOINTER_TO_INT’
576 |    count = GPOINTER_TO_INT (g_hash_table_lookup (mate_language_count_map, locale->language_code));
| …
```
> Remove warning -Wbad-function-cast

- libmate-desktop/mate-bg.c
- libmate-desktop/mate-rr-config.c
- libmate-desktop/mate-rr.c
```
mate-bg.c:3074:7: warning: declaration of ‘len’ shadows a previous local [-Wshadow]
3074 |   int len;
|       ^~~
mate-bg.c:3035:8: note: shadowed declaration is here
--
mate-rr.c:379:14: warning: declaration of ‘crtc’ shadows a previous local [-Wshadow]
379 |  MateRRCrtc *crtc = crtc_new (info, resources->crtcs[i]);
|              ^~~~
mate-rr.c:368:18: note: shadowed declaration is here
--
mate-rr.c:389:16: warning: declaration of ‘output’ shadows a previous local [-Wshadow]
389 |  MateRROutput *output = output_new (info, resources->outputs[i]);
|                ^~~~~~
mate-rr.c:369:20: note: shadowed declaration is here
--
mate-rr-config.c:1549:12: warning: declaration of ‘info’ shadows a previous local [-Wshadow]
1549 |  CrtcInfo *info = g_new0 (CrtcInfo, 1);
|            ^~~~
```
> Remove shadow warnings [-Wshadow]

- mate-about/mate-about.c
The MATE About program is designed to display one of six messages at random
each time you launch the application, showcasing the fundamental values of
the MATE Project.  Unfortunately, due to an off-by-one programming error
introduced many years ago, only the first five messages ever get displayed;
the sixth message, referring to where MATE got its name from, is never chosen.
This was due to a misunderstanding of the GLib function `g_random_int_range`:
The function is and always was designed to be passed an inclusive lower and
an exclusive upper value for the random integer, generating a random integer
that is greater than or equal to the lower value and less than the upper value
specified.  The MATE About application errantly subtracted 1 from the upper
value itself, and thus only …
> MATE About: Fix off-by-one error, display yerba mate comment

- schemas/org.mate.sound.gschema.xml
There is often a need for the user to increase the audio playback volume above
the volume level known as "100% volume".  While increasing the audio volume
above 100% can result in degraded audio quality, sometimes the audio was, for
example, originally recorded at an extremely low volume, and the user has no
other option to clearly hear the audio.  Unfortunately, most MATE applications
with volume controls do not allow the user to set the volume level above 100%.
For example, the main MATE Sound Preferences dialog lets you set the audio
volume beyond 100% (when possible), whereas the Volume Control Applet, Volume
Control status icon, and special "multimedia" volume control keys do not.  In
fact, if the user even tries to change the volume using any of the latter
methods, and the current …
> Add setting for adjustment of audio volume above 100 per cent:  Part 1

- libmate-desktop/mate-colorbutton.c
```
mate-colorbutton.c:298:45: warning: implicit conversion from enumeration type 'GtkStateType' to different enumeration type 'GtkStateFlags' [-Wenum-conversion]
gtk_style_context_get_color (context, GTK_STATE_INSENSITIVE, &rgba);
~~~~~~~~~~~~~~~~~~~~~~~~~~~           ^~~~~~~~~~~~~~~~~~~~~
```
> mate-colorbutton: fix -Wenum-conversion warning

- libmate-desktop/mate-bg.c
- libmate-desktop/mate-colorsel.c
- libmate-desktop/mate-desktop-item.c
```
mate-bg.c:81:9: warning: macro is not used [-Wunused-macros]
#define GRADIENT_PIXMAP_TILE_SIZE 128
^
--
mate-colorsel.c:57:9: warning: macro is not used [-Wunused-macros]
#define SAMPLE_HEIGHT 28
^
mate-colorsel.c:56:9: warning: macro is not used [-Wunused-macros]
#define SAMPLE_WIDTH  64
^
--
mate-desktop-item.c:55:9: warning: macro is not used [-Wunused-macros]
#define sure_string(s) ((s)!=NULL?(s):"")
^
```
> Remove some build warnings about unused macros

- libmate-desktop/mate-colorsel.c
- mate-about/mate-about.h.in
```
mate-colorsel.c:901:32: warning: missing field 'info' initializer [-Wmissing-field-initializers]
{ "application/x-color", 0 }
^
--
mate-colorsel.c:1268:29: warning: missing field 'info' initializer [-Wmissing-field-initializers]
{ "application/x-color", 0 }
^
--
mate-colorsel.c:1551:32: warning: missing field 'info' initializer [-Wmissing-field-initializers]
{ "application/x-color", 0 }
^
--
./mate-about.h:667:10: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{NULL}
^
```
> Fix build warnings about missing field initializer

- libmate-desktop/mate-colorbutton.c
- libmate-desktop/mate-colorsel.c
```
CFLAGS="-Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
```
mate-colorbutton.c:766:39: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
color_button->priv->use_alpha = use_alpha;
~ ^~~~~~~~~
--
mate-colorsel.c:2339:27: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
priv->has_opacity = has_opacity;
~ ^~~~~~~~~~~
mate-colorsel.c:2398:27: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
priv->has_palette = has_palette;
~ ^~~~~~~~~~~
```
> Fix implicit conversion changes signedness: 'gboolean' to 'guint'

- libmate-desktop/mate-bg.c
It is not possible to use the `list` pointer after it has been deleted, so the "cleanup" this commit made lead to using freed memory if any item actually got clean up.
This "cleanup" also don't seem meaningful to me, as all it does otherwise is trade an assignation for a redundant test -- either of which the compiler might happily optimize out.
This reverts commit 47426c90d10e9f738ecf89f35db94ca8deff55e0.
> Revert "[mate-bg] small cleanup"

- docs/reference/mate-desktop/mate-desktop-docs.sgml
- docs/reference/mate-desktop/mate-desktop-sections.txt
- libmate-desktop/Makefile.am
- libmate-desktop/mate-desktop.abi
- libmate-desktop/mate-image-menu-item.c
- libmate-desktop/mate-image-menu-item.h
- libmate-desktop/meson.build
- libmate-desktop/test-image-menu-item.c
Add ```mate_image_menu_item``` apis to replace ```gtk_image_menu_item``` to remove deprecated compilation warnings
After this PR is merged, I will gradually replace the deprecated ```gtk_image_menu_item``` in other projects
#550 
run ```test-image-menu-item``` command
> Add mate image menu item apis

- libmate-desktop/mate-bg.c
*put XKillClient and gdk_x11_screen_get_xscreen behind x11-only runtime checks
> Initial support for showing a caja desktop in wayland

- Makefile.am
- configure.ac
- meson.build
- xdg-portal/Makefile.am
- xdg-portal/mate-portals.conf
- xdg-portal/meson.build
fixes https://github.com/mate-desktop/mate-desktop/issues/574
This installs a mate-portals.conf for xdg-desktop-portal >= 1.17, indicating that MATE recommended portal backend for use with MATE. Recommendation is currently [x-d-p-gtk](https://github.com/flatpak/xdg-desktop-portal-gtk).
Edit:
The mate.portals.conf file is a replacement for the UseIn key inside the portal implementation files; it is also a replacement for people disabling unwanted portal support.
> add xdg-desktop-portal config file

- meson.build
- meson_options.txt
Fix https://github.com/mate-desktop/mate-desktop/issues/570
> Add meson build libstartup-notification support

- libmate-desktop/mate-colorseldialog.c
```gtk_dialog_get_action_area``` has been deprecated
> mate-colorseldialog: Fix compilation warnings remove deprecated function

- libmate-desktop/mate-desktop-item.c
We still have sn_display in the runtime checks to determine whether to call the startup notification, so we have to initialize it to NULL in the wayland case.
> wayland: fix uninitialized variable

- libmate-desktop/mate-bg-crossfade.c
- libmate-desktop/mate-desktop-utils.c
Fix compilation warning，Test normal using ```mate-display-properties```
> Fix compilation warning replace gtk_style_context_get_background_color

- xdg-portal/Makefile.am
Follow-up of 287fdce6d430 ("add xdg-desktop-portal config file")
Unbreaks meson build using release tarball:
```
meson.build:109:0: ERROR: Nonexistent build file 'xdg-portal/meson.build'
```
Closes #600
Tested make dist :
Tested building with autotools and meson using the tarball
> xdg-portal: add meson.build to EXTRA_DIST

- libmate-desktop/mate-image-menu-item.c
This was used in GtkImageMenuItem to support stock items, but this is a deprecated feature that didn't make it to MateImageMenuItem.  Now, this is entirely unused, and just leads to glue code maintaining an unused local copy of the label, effectively wasting a little bit of memory and adding complexity.
Just drop all references to it, without any functional difference.
See also https://github.com/mate-desktop/mate-panel/issues/1433#issuecomment-1969918905
> MateImageMenuItem: Remove unnecessary label field
