libmate-desktop/mate-desktop-thumbnail.c

Backport @mtwebster 's fix for crashes for bad image types
https://github.com/linuxmint/cinnamon-desktop/commit/f7927e9a8201761b6654955739e87b93d3695169
caja bug reports
https://bugzilla.redhat.com/show_bug.cgi?id=1206985
https://bugzilla.redhat.com/show_bug.cgi?id=1231446

backport cinnamon-desktop fix for buggy image types

---

libmate-desktop/mate-bg.c
libmate-desktop/mate-rr.c
libmate-desktop/mate-rr.h

@NiceandGently @infirit @flexiondotorg 
please test for any possible regressions :smile:

Some upstream fixes

---

schemas/org.mate.interface.gschema.xml.in

Related:
* https://github.com/mate-desktop/mate-settings-daemon/pull/210
* https://github.com/mate-desktop/mate-control-center/pull/329
* https://github.com/ubuntu-mate/mate-tweak/pull/39

Add gsettings for window scaling factor

---

libmate-desktop/mate-bg-crossfade.c
libmate-desktop/mate-bg.c
libmate-desktop/mate-desktop-item.c
libmate-desktop/mate-rr-config.c
libmate-desktop/mate-rr.c

fix deprecated GdK functions

---

mate-about/mate-about.h

I think it's time to update copyright  to 2019.

update copyright  to 2019

---

libmate-desktop/mate-colorsel.c
libmate-desktop/mate-colorsel.h

Fixed deprecated api g_type_class_add_private

[mate-colorsel] Avoid deprecated g_type_class_add_private

---

libmate-desktop/mate-bg-crossfade.c
libmate-desktop/mate-colorbutton.c
libmate-desktop/mate-desktop-thumbnail.c

Changed MateBgCrossfade, MateColorbutton and MateDesktopThumbnail

Avoid deprecated g_type_class_add_private

---

libmate-desktop/mate-rr-config.c
libmate-desktop/mate-rr-labeler.c
libmate-desktop/mate-rr-output-info.c
libmate-desktop/mate-rr.c

Please review and test it. Thanks.

[mate-rr] Avoid deprecated g_type_class_add_private

---

.travis.yml

Support archlinux、debian、fedora and ubuntu.

Initialize travis support

---

docs/reference/mate-desktop/mate-desktop-sections.txt
libmate-desktop/Makefile.am
libmate-desktop/mate-colorsel.c
libmate-desktop/mate-hsv.c
libmate-desktop/mate-hsv.h
po/POTFILES.in

Note: we have a lot of lines here, please don't merge to the 1.22 release

MateHSV implementation (GtkHSV fork)

---

.travis.yml

@raveit65 
Please enable gh-pages branch for pages, thanks.

[ci] Enable Clang Static Analyzer

---

libmate-desktop/Makefile.am
libmate-desktop/mate-languages.c
libmate-desktop/mate-languages.h
libmate-desktop/meson.build
libmate-desktop/test-languages.c
meson.build

Add test code for mate-languages.

Add test code for mate-languages

---

libmate-desktop/mate-colorbutton.c
libmate-desktop/mate-colorsel.c
libmate-desktop/mate-colorseldialog.c
libmate-desktop/mate-dconf.c
libmate-desktop/mate-desktop-thumbnail.c
libmate-desktop/mate-gsettings.c
libmate-desktop/mate-hsv.c
libmate-desktop/mate-rr-config.c
libmate-desktop/mate-rr-config.h
libmate-desktop/mate-rr-private.h
libmate-desktop/mate-rr.c
libmate-desktop/mate-rr.h
libmate-desktop/mate-thumbnail-pixbuf-utils.c
libmate-desktop/test.c
tools/mate-color-select.c

`find . -regextype posix-extended -regex '.*\.(c|h|ac)' -exec sed --in-place 's/[[:space:]]\+$//' {} \+`
like rbuj do on [https://github.com/mate-desktop/mate-control-center/pull/463](https://github.com/mate-desktop/mate-control-center/pull/463).

Remove trailing whitespaces

---

libmate-desktop/mate-bg-crossfade.c
libmate-desktop/mate-bg-crossfade.h

Replace deprecated gtk css provider get default

---

meson_options.txt

meson: add configuration item description

---

schemas/org.mate.accessibility-keyboard.gschema.xml

a11y-keyboard: Add more togglekeys settings for an alternate backend

---

libmate-desktop/mate-colorbutton.c
libmate-desktop/mate-colorseldialog.c
libmate-desktop/mate-rr.c
tools/mate-color-select.c

I fixed some compilation warnings  replaced some outdated API.
Next I'll use ```gdk_raba``` replaces ```gdk_color```

Fix compilation warning

---

libmate-desktop/mate-colorsel.c

Replace the obsolete API in mate-colorsel.c file 
Use ```gdk_seat``` and ```gdk_device``` replace ```gdk_display```
I can't provide a test program to test whether this change is correct

Replace the obsolete API in mate-colorsel.c file

---

libmate-desktop/mate-desktop-item.c

*Wrap the startup notification code in an x11-only conditional block 
*This is x11-specific code, so don't try to run it outside of x11

desktop-item: limit startup notification to x11

---

libmate-desktop/mate-desktop.abi

Fix ninja test symbols check FAIL

---

configure.ac
libmate-desktop/mate-desktop.h.in
libmate-desktop/meson.build

Add version macros for use by other applications

Add MATE_DESKTOP_VERSION marco

---

libmate-desktop/mate-image-menu-item.c
libmate-desktop/mate-image-menu-item.h

See the discussion on:https://github.com/mate-desktop/mate-panel/issues/1433

Make MateImageMenuItem subclassable

---

libmate-desktop/mate-colorsel.c
schemas/org.mate.interface.gschema.xml

solves: mate-color-select doesn't work (as expected) #643

Fix palette
